### ISSUE TITLE
Add cl_autowepswitch command

### ISSUE THREAD

**Issue by segreee** [ntrf/blamod#22]
When a player picks up a new weapon that's "better" than the current one, the game is switching to the new weapon automatically.
This command exists in HL2DM but it's not present in Half-Life 2 and this mod.

**Comment by ntrf** [comment]
Yes. `cl_autowepswitch` is implemented for multiplayer games only. Still this should be easy enough to fix.

FYI There is a variable `blamod_autowepswitch`, which disables switching when you pickup ammo, but not when you pickup a new gun.
