### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by helpmeiminabasement** [ntrf/blamod#25]
It's only one map and it doesn't even load. Did I do something wrong?

69 74 20 68 75 72 74 73

**Comment by ntrf** [comment]
Scince version 12, Blamod Rebond comes with SDK-only maps (including hl2 maps would be license violation), but supports dynamic mounting of game data for HL2 and episodes. If you have HL2 or episodes installed, you can mount them with console command `blamod_mount hl2/ep1/ep2`. You can copy that line into your `userconfig.cfg` file to keep game mounted from the start. I'm going to make a UI for easier switching eventually.

More info here: https://github.com/ntrf/blamod/wiki/Episodes-support

6D 65 20 74 6F 6F
