### ISSUE TITLE
(Reupload) Softlocking animation Point Insertion Alyx

### ISSUE THREAD

**Issue by helpmeiminabasement** [ntrf/blamod#27]
NPC alyx using alternate collision! -- DISABLED
alyx: unknown scripted sequence "intro_bendover"
Dynamic prop blackout: no sequence named:exit1
CSceneEntity alyx :"Alyx" unable to find gesture "A_gesture13"

Pretty much, after you get beat up by the cops, the camera just looks down and you cannot move at all. Loading a previous save fixes the issue until you get to the same part, where it happens again.

00110110 01100110 00100000 00110110 01100110 00100000 00110110 00110110 00100000 00110010 00110000 00100000 00110110 01100110 00100000 00110111 00110111 00100000 00110110 00111001 00100000 00110110 00110101 00100000 00110010 00110000 00100000 00110110 01100100 00100000 00110111 00111001 00100000 00110010 00110000 00100000 00110110 00110010 00100000 00110110 01100110 00100000 00110110 01100101 00100000 00110110 00110101 00100000 00110111 00110011 00100000

**Comment by ntrf** [comment]
Can you provide a save file?

**Comment by helpmeiminabasement** [comment]
[](https://www.dropbox.com/sh/6jog23za75380yd/AABPoft3DQJbZmjI2NbWpNtia?dl=0)

**Comment by helpmeiminabasement** [comment]
Sooo.... any updates?

**Comment by ntrf** [comment]
Finally got time to check this out. 
I used fresh installation of both HL2 and Blamod Reborn. I've tried both starting game from scratch and using saves you've provided.

I can't reproduce the issue. Cutscene works just fine.

As with many simmilar issues i suspect you have a spliced game. Either you have modified maps installed in your HL2, or you've copied maps from HL2 into Blamod Reborn. If later is the case, you should reinstall and use `blamod_mount hl2` command instead. There is no UI for that action available at the moment, so yo have to do it by hand. If you have modified hl2, you can restore it by using Verify cache Integrity feature in steam.

A reminder that as of now rules for all HL2 games and mods forbid game splicing. If you're playing game, based on specific version of Source SDK, you should use matching maps. Blamod Reborn is based on Steampipe and Source SDK 2013, which means you should use it with HL2 post-Steampipe update maps (which is available on Steam right now).
